/* Generated by Yosys 0.59+0 (git sha1 529886f7fb8f0dd6339bca470a01db5e289755b5, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module d27(N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N11);
  input N1;
  wire N1;
  input N2;
  wire N2;
  input N3;
  wire N3;
  input N4;
  wire N4;
  output N5;
  wire N5;
  output N6;
  wire N6;
  output N7;
  wire N7;
  output N8;
  wire N8;
  output N9;
  wire N9;
  output N10;
  wire N10;
  output N11;
  wire N11;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  INV_X1 _22_ (
    .A(N3),
    .ZN(_0_)
  );
  NOR2_X1 _23_ (
    .A1(N4),
    .A2(_0_),
    .ZN(_1_)
  );
  NOR2_X1 _24_ (
    .A1(_0_),
    .A2(N1),
    .ZN(_2_)
  );
  INV_X1 _25_ (
    .A(N2),
    .ZN(_3_)
  );
  MUX2_X1 _26_ (
    .A(_0_),
    .B(_2_),
    .S(_3_),
    .Z(_4_)
  );
  NOR2_X1 _27_ (
    .A1(_1_),
    .A2(_4_),
    .ZN(N11)
  );
  INV_X1 _28_ (
    .A(N4),
    .ZN(_5_)
  );
  NOR2_X1 _29_ (
    .A1(N1),
    .A2(_3_),
    .ZN(_6_)
  );
  NOR3_X1 _30_ (
    .A1(_5_),
    .A2(N3),
    .A3(_6_),
    .ZN(_7_)
  );
  NOR3_X1 _31_ (
    .A1(N4),
    .A2(N1),
    .A3(_3_),
    .ZN(_8_)
  );
  INV_X1 _32_ (
    .A(N1),
    .ZN(_9_)
  );
  NOR2_X1 _33_ (
    .A1(_9_),
    .A2(N2),
    .ZN(_10_)
  );
  NOR3_X1 _34_ (
    .A1(_0_),
    .A2(_8_),
    .A3(_10_),
    .ZN(_11_)
  );
  NOR2_X1 _35_ (
    .A1(_7_),
    .A2(_11_),
    .ZN(N10)
  );
  NOR2_X1 _36_ (
    .A1(N4),
    .A2(N2),
    .ZN(_12_)
  );
  OR3_X1 _37_ (
    .A1(_2_),
    .A2(_6_),
    .A3(_12_),
    .ZN(N9)
  );
  NOR2_X1 _38_ (
    .A1(_2_),
    .A2(_12_),
    .ZN(_13_)
  );
  NAND2_X1 _39_ (
    .A1(N3),
    .A2(_3_),
    .ZN(_14_)
  );
  NAND3_X1 _40_ (
    .A1(N4),
    .A2(N1),
    .A3(_14_),
    .ZN(_15_)
  );
  NAND2_X1 _41_ (
    .A1(_13_),
    .A2(_15_),
    .ZN(N8)
  );
  NOR2_X1 _42_ (
    .A1(_5_),
    .A2(N2),
    .ZN(_16_)
  );
  NOR2_X1 _43_ (
    .A1(_6_),
    .A2(_16_),
    .ZN(N7)
  );
  XNOR2_X1 _44_ (
    .A(N4),
    .B(N3),
    .ZN(_17_)
  );
  XNOR2_X1 _45_ (
    .A(_9_),
    .B(_17_),
    .ZN(N6)
  );
  NOR2_X1 _46_ (
    .A1(_0_),
    .A2(_10_),
    .ZN(_18_)
  );
  XNOR2_X1 _47_ (
    .A(N1),
    .B(N2),
    .ZN(_19_)
  );
  NOR3_X1 _48_ (
    .A1(_5_),
    .A2(N3),
    .A3(_19_),
    .ZN(_20_)
  );
  NOR2_X1 _49_ (
    .A1(N4),
    .A2(_6_),
    .ZN(_21_)
  );
  OR3_X1 _50_ (
    .A1(_18_),
    .A2(_20_),
    .A3(_21_),
    .ZN(N5)
  );
endmodule
