/* Generated by Yosys 0.59+0 (git sha1 529886f7fb8f0dd6339bca470a01db5e289755b5, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1;
  wire N1;
  input N2;
  wire N2;
  input N3;
  wire N3;
  input N6;
  wire N6;
  input N7;
  wire N7;
  output N22;
  wire N22;
  output N23;
  wire N23;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  NAND2_X2 _4_ (
    .A1(N6),
    .A2(N3),
    .ZN(_2_)
  );
  NAND2_X4 _5_ (
    .A1(N2),
    .A2(_2_),
    .ZN(_3_)
  );
  NAND2_X2 _6_ (
    .A1(N7),
    .A2(_2_),
    .ZN(_0_)
  );
  NAND2_X2 _7_ (
    .A1(_3_),
    .A2(_0_),
    .ZN(N23)
  );
  NAND2_X2 _8_ (
    .A1(N3),
    .A2(N1),
    .ZN(_1_)
  );
  NAND2_X2 _9_ (
    .A1(_3_),
    .A2(_1_),
    .ZN(N22)
  );
endmodule
